server:
  port: '5000'
topic:
  name: t.user.details
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  config:
    import: optional:configserver:http://18.119.76.13:5000
  application:
    name: user-registration
  doc:
    swagger-ui:
      path: /swagger-ui
  devtools:
    restart:
      enabled: 'true'
