server:
  port: '5000'
jwt:
  secret: secret
topic:
  name: t.user.details
spring:
  kafka:
    consumer:
      group-id: "default"
  application:
    name: login-service
  config:
    import: optional:configserver:http://3.143.151.64:5000
  doc:
  swagger-ui:
  path: /swagger-ui


